Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2019-05, with the labels that each got.

#471 Upgrade common to 2.0.7
  build.gradle
Labels: ns:sscs-tya-notif-pr-471

#481 Remove PR bump
  Jenkinsfile_CNP
Labels: ns:sscs-tya-notif-pr-481

#487 Fix product and component variables
  Jenkinsfile_CNP
Labels: ns:sscs-tya-notif-pr-487

#485 SSCS-5233 - Helm charts
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  build.gradle
  charts/sscs-tya-notif/Chart.yaml
  charts/sscs-tya-notif/requirements.yaml
  charts/sscs-tya-notif/values.aat.template.yaml
  charts/sscs-tya-notif/values.template.yaml
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/controller/LivenessControllerTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/controller/LivenessController.java
  src/main/resources/bootstrap.yaml
Labels: ns:sscs-tya-notif-pr-485

#447 SSCS-5321, SSCS-5322, SSCS-5323, SSCS-5325, SSCS-5326, SSCS-5327, SSC…
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReminderNotificationsFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
Labels: ns:sscs-tya-notif-pr-447

#488 SSCS-5380 Remove hearing holding reminders from Quartz
  src/main/resources/db/migration/V20190508_02__reminders-removal.sql
Labels: ns:sscs-tya-notif-pr-488

#473 SSCS-5481 Notification - Hearing reminder notification was sent out w…
  dependency-check-suppressions.xml
  src/main/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingReminder.java
  src/test/java/uk/gov/hmcts/reform/sscs/SscsCaseDataUtils.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/reminder/HearingReminderTest.java
Labels: ns:sscs-tya-notif-pr-473

#492 Use rpc phone number v2
  src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationConfig.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/CohPersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/SubscriptionPersonalisationTest.java
Labels: ns:sscs-tya-notif-pr-492

#502 upgrade common
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs-tya-notif-pr-502

#508 remove RC from master
  build.gradle
Labels: ns:sscs-tya-notif-pr-508

#496 SSCS-5512 Bundled Rep letters
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceForSubscriptionUpdatedTest.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/CohNotificationsIt.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/OutOfHoursIt.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/BundledLetterTemplateUtil.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/service/BundledLetterTemplateUtilTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java
Labels: ns:sscs-tya-notif-pr-496
