Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2020-08, with the labels that each got.

#1029 SSCS-7634: Tech debt – Change PDF service URL from CMC to RPE
  charts/sscs-tya-notif/Chart.yaml
  charts/sscs-tya-notif/values.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1029

#1079 SSCS-7790 Adding Adjourn Case Reissue Handling
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1079

#1082 SSCS-7866 Changing ISSUE_ADJOURNMENT to ISSUE_ADJOURNMENT_NOTICE
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
  src/e2e/resources/issueAdjournmentNoticeCallback.json
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactory.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationUtils.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationValidService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java
  src/test/resources/json/ccdResponse_issueAdjournmentNotice.json
  src/test/resources/json/ccdResponse_issueAdjournmentNotice_withAppointee.json
  src/test/resources/json/ccdResponse_issueAdjournmentNotice_withRep.json
  src/test/resources/json/ccdResponse_issueAdjournmentNotice_withRep_withAppointee.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1082

#1069 Wla 554 v1
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationConfig.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/Notification.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/Template.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationUtils.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1069

#1092 suppress CVE-2020-15824 for a month
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1092

#1070 Sscs 7410 - Removing COR/COH Notifications, logic, controllers and tests
  src/IntegrationTests/java/helper/IntegrationTestHelper.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/controller/NotificationControllerTest.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/AbstractFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/CohNotificationFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java
  src/main/java/uk/gov/hmcts/reform/sscs/controller/NotificationController.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/CohEvent.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/CohNotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactory.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/CohPersonalisation.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/CohActionExecutor.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/controller/NotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventTypeTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/CohPersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationValidServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/scheduler/CohActionExecutorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1070

#1107 Revert "Bump postgresql from 42.2.14 to 42.2.15"
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1107

#1105 Enable functional tests in nightly pipeline
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1105

#1110 Remove s from test url
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1110

#1111 SSCS-7535 Up commons for isScottish
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1111

#1118 Fix nightly tests
  Jenkinsfile_nightly
  charts/sscs-tya-notif/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1118

#1119 added urls
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1119

#1093 SSCS-7309 - Set 'Previous State' field when case moves to dormant
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1093

#1104 SSCS-7776 - Appointee letters are still sent when an Appointee is removed from a case
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/SyaAppealCreatedAndReceivedPersonalisation.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationUtils.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationUtilsTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1104

#1040 SSCS-7696 - Notifications – Have a retry mechanism on the queue
  src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/AdminAppealWithdrawnNotificationsEventsHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/RetryConfig.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationSender.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/RetryNotificationService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/BaseActionExecutor.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/scheduler/CcdActionExecutor.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/AdminAppealWithdrawnNotificationsEventsHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationSenderTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/RetryNotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/scheduler/CcdActionExecutorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1040

#1132 Remove unused tf remote state
  infrastructure/state.tf
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1132

#1134 updated severity from High to Medium
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1134

#1135 updated audit.json
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1135
