Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2021-06, with the labels that each got.

#1653 Verify we have removed enough of the suppressions
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1653

#1648 SSCS-8820 - JSA DWP Office Address
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1648

#1657 SSCS-9262 - Notification – Turning off hearingPostponed while we fix SSCS-9191
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1657

#1665 SSCS-9286 - handle null events
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1665

#1649 SSCS-9151 Issue generic letter to specified party
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WelshNotificationsFunctionalTest.java
  src/e2e/resources/requestInfoIncompleteApplicationCallback.json
  src/e2e/resources/requestInfoIncompleteApplicationCallbackWelsh.json
  src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java
  src/test/resources/json/ccdResponse_requestInfoIncomplete.json
  src/test/resources/json/ccdResponse_requestInfoIncompleteAppellant.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1649

#1697 suppress CVE-2021-33813
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1697

#1690 SSCS-9305 Refactor after moving deprecated fields
  build.gradle
  src/test/java/uk/gov/hmcts/reform/sscs/service/scheduler/CcdActionExecutorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1690

#1703 CVE-2021-31811 - fix
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1703

#1705 update security script
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1705
