Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2021-05, with the labels that each got.

#1610 dependency-check-suppressions
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1610

#1565 SSCS-8985: Notifications – AAT – Endless loop is happening for notifi…
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsItBase.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/OutOfHoursIt.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationSender.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SaveCorrespondenceAsyncService.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationSenderTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SaveCorrespondenceAsyncServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1565

#1580 SSCS-8900 - Attendance Allowance - Airlookup, DWP addresses & Robot Configuration
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1580

#1613 Suppress false positive CVE-2020-7791 since it is a C# CVE
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1613

#1593 sscs 8879 update common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1593

#1616 sscs 9066 jitpack move
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1616

#1624 Sscs 9066 jitpack
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1624

#1618 SSCS-9154 - Carer's Allowance - Panel List for Notification Content
  build.gradle
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1618

#1630 Suppress sec warnings
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1630

#1640 SSCS-9197 Remove benefit word from notifications
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1640

#1636 sscs-9044 update templates to the right ones
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1636

#1641 SSCS-8906 Bereavement benefit DWP mappings
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1641

#1642 SSCS-9201 Welsh DWP translation
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/SubscriptionPersonalisationTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1642

#1637 SSCS-9041 - CCD UI – Validate DWP originating and presenting office for the 'Response reviewed' event
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1637

#1617 SSCS-9122 upgrade common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1617
