Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2021-03, with the labels that each got.

#1470 SSCS-8138 - Remove COR templates
  build.gradle
  dependency-check-suppressions.xml
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/AppealHearingType.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/ReminderService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/ReminderServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1470

#1479 SSCS-8750 - Dwp Document Sorting
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1479

#1485 fixed the dependnecy check
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1485

#1486 Updated pdf service to point to docmosis-aat url while running local
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1486

#1481 SSCS-8738: Notification – Scheduling notification seems to take way t…
  build.gradle
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1481

#1494 upgrade tomcat version to fix depedency check
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1494

#1497 SSCS-8862: Notifications – Reminder service – scale up resources temp…
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1497

#1498 SSCS-8752 - Issue Directions Notice - Send to all Parties
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
  src/e2e/resources/processAudioVideoCallback.json
  src/e2e/resources/processAudioVideoWelshCallback.json
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactory.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationValidService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java
  src/test/resources/json/ccdResponse_processAudioVideo.json
  src/test/resources/json/ccdResponse_processAudioVideoWelsh.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1498

#1502 SSCS-8867: Notification – Reminders are scheduled to run at 12am
  src/main/java/uk/gov/hmcts/reform/sscs/extractor/DwpResponseReceivedDateExtractor.java
  src/test/java/uk/gov/hmcts/reform/sscs/extractor/DwpResponseReceivedDateExtractorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1502

#1517 SSCS-8856 - Enhance the logs when Notify comes back with an error
  src/main/java/uk/gov/hmcts/reform/sscs/exception/NotificationServiceException.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1517

#1514 SSCS-8878 DLA Panel Composition
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
  src/e2e/resources/paper/responseReceived/dla-paper-responseReceivedCallback.json
  src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1514

#1506 SSCS-8857- No Welsh translation for final decision notice
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
  src/e2e/resources/issueFinalDecisionWelshCallback.json
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactory.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationValidService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java
  src/test/resources/json/ccdResponse_issueFinalDecisionWelsh.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1506

#1528 Remove unused dependency suppression
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1528

#1529 Dependency suppression
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1529

#1532 Bump rest-assured to 4.3.3
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1532

#1525 SSCS-8894:Carer's Allowance - Airlookup, DWP addresses & Robot Config…
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1525

#1534 DTSPO-1792 Switch common from bintray to jitpack
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1534
