Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2021-07, with the labels that each got.

#1706 Suppress for one more month
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1706

#1710 SSCS-9338 Translation for welsh word for joint
  src/main/java/uk/gov/hmcts/reform/sscs/config/AppConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1710

#1709 SSCS-9349 Split issue final decision welsh into 2
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTestIt.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationConfig.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/NotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/NotificationFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
  src/test/resources/json/ccdResponse_issueFinalDecisionWelsh_withRep.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1709

#1704 SSCS-9334- Notification – Stop the responseReceived going out for digital cases
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/JointPartyFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WelshNotificationsFunctionalTest.java
  src/e2e/resources/jointParty/oral-dwpUploadResponseCallback.json
  src/e2e/resources/jointParty/paper-dwpUploadResponseCallback.json
  src/e2e/resources/oral-dwpUploadResponseCallback.json
  src/e2e/resources/oral-dwpUploadResponseCallbackWelsh.json
  src/e2e/resources/paper-dwpUploadResponseCallback.json
  src/e2e/resources/paper-dwpUploadResponseCallbackWelsh.json
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1704

#1715 SSCS-9061-updated common with social fund benefit
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1715

#1694 SSCS-9308 - CCD UI – Setting the ESA and UC dwpRegionalCentre
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1694

#1723 SSCS-8924 - Income Support
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1723

#1714 SSCS-9362 - case document am
  build.gradle
  charts/sscs-tya-notif/Chart.yaml
  charts/sscs-tya-notif/values.yaml
  src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1714

#1736 fix-dc
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1736

#1724 sscs 8708 secure docstore download
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceBase.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsItBase.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/OutOfHoursIt.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1724

#1731 SSCS-9420 - Update doc store client
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/TrackYourAppealNotificationsApplication.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1731

#1743 SSCS-9213 Add other benefits
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1743

#1757 Update README.md
  README.md
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1757
