Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2022-04, with the labels that each got.

#2044 Update SSCS Commons to 4.7.0
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2044

#2047 SSCS Commons 4.7.1 Upgrade
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2047

#2052 SSCS-10220 Update to common RC version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2052

#2062 SSCS-10376-Fix-Nightly-Build: supressions and upgrades
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2062

#2056 SSCS-10376 Fix build
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/config/SwaggerConfiguration.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/controller/ReminderTestController.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2056

#2049 SSCS-10146 update sscs-common version
  build.gradle
  dependency-check-suppressions.xml
  src/test/java/uk/gov/hmcts/reform/sscs/controller/ReminderTestController.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2049

#2059 SSCS-10387 Update Commons
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2059
