Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2022-08, with the labels that each got.

#2145 extend dep suppression
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2145

#2148 SSCS-10805-jar-version-update
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2148

#2155 SSCS-10773: Update commons version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2155

#2163 chore: increment sscs-common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2163

#2152 sscs-9874-common-version-update
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2152

#2164 Add backstage configuration file
  catalog-info.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2164

#2167 SSCS-10841 Common bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2167
