Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2022-02, with the labels that each got.

#1992 Update sscs-commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-1992

#2007 upgrade helms chart
  charts/sscs-tya-notif/Chart.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2007

#2009 Update sscs-common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2009
