Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2022-10, with the labels that each got.

#2201 SSCS-10968 cve suppression
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2201

#2172 SSCS-10887 Tool for Rendering Docmosis Letters
  .gitignore
  README.md
  bin/render-docmosis-template.ps1
  bin/render-docmosis-template.sh
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2172

#2200 SSCS-10985 CVE Fix Commons Bump
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2200

#2213 Commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2213

#2214 SSCS-11008 - Add content type and tags to secrets
  .gitignore
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, add-or-update, rel:sscs-tya-notif-pr-2214

#2043 Create CODEOWNERS
  CODEOWNERS
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2043

#2191 SSCS-10924 Use tf managed secret.
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/sscs-tya-notif/Chart.yaml
  charts/sscs-tya-notif/values.preview.template.yaml
  charts/sscs-tya-notif/values.yaml
  src/main/resources/bootstrap.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2191
