Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2022-07, with the labels that each got.

#2133 SSCS-10706 Common bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2133

#2132 SSCS-10746-tika-cve-fix : update tike core
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2132

#2138 SSCS-10087 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2138

#2137 sscsBaseChartUpdate-Java401
  charts/sscs-tya-notif/Chart.yaml
  charts/sscs-tya-notif/values.preview.template.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2137

#2141 TF 0.13.7
  infrastructure/.terraform-version
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2141
