Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2022-05, with the labels that each got.

#2069 SSCS-10223 commons bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2069

#2057 SSCS-10388 Update Commons
  build.gradle
  dependency-check-suppressions.xml
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceBase.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/LetterUtils.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationUtils.java
  src/test/java/uk/gov/hmcts/reform/sscs/SscsCaseDataUtils.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/LetterUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SendNotificationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2057

#2071 SSCS-10444 Change CVE Reporting
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2071

#2073 Sscs 10443 azure tagging appeal notifications
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2073

#2075 SSCS-10503: Fix Nightly Build
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2075

#2077 Update dependency-check-suppressions.xml
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2077

#2076 SSCS-10490 bump common
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2076

#2079 sscs-10355 bump sscs common version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2079

#2084 SSCS-10555: Upgrading Spring Core
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2084

#2095 update commons version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2095

#2096 Sscs 10568 fix suppression
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2096
