Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2022-06, with the labels that each got.

#2109 SSCS-10445 Commons Bump
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2109

#2111 Update build.gradle
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2111

#2113 SSCS-10468: Update dependency suppressions
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2113

#2116 SSCS-10286 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2116

#2120 SSCS-10643-Reference Data Update
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2120

#2121 SSCS-10620 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2121

#2122 SSCS-10242 Commons Bump
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2122

#2127 Commons Automation
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2127
