Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2023-11, with the labels that each got.

#2430 CVE Fix 06.11.2023
  build.gradle
  charts/sscs-tya-notif/Chart.yaml
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2430

#2429 SSCSCI-514: add postgres flexible server terraform config
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:sscs, prd:sscs, add-or-update, rel:sscs-tya-notif-pr-2429

#2431 DTSPO-15872 Fix DB config for AAD access
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, add-or-update, rel:sscs-tya-notif-pr-2431
