Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2023-06, with the labels that each got.

#2320 SSCS-10188 - Judicial- CCD- Select the recipients of Directions Notice
  build.gradle
  dependency-check-suppressions.xml
  src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/NotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/LetterUtils.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/LetterUtilsTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2320

#2381 CVE Suppression - 12.06.2023
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2381

#2382 SSCS-10973 - rename requestInfoIncompleteApplication to Requestforinformation
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTestIt.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsDelayedNotificationsIt.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WelshNotificationsFunctionalTest.java
  src/e2e/resources/requestForInformationCallback.json
  src/e2e/resources/requestForInformationCallbackWelsh.json
  src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationEventTypeLists.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
  src/test/resources/json/ccdResponse_requestForInformation.json
  src/test/resources/json/ccdResponse_requestForInformationAppellant.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2382

#2395 CVE Fix.27.06.23
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2395

#2396 CVE Fix - 30.06.23
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2396
