Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2023-04, with the labels that each got.

#2335 CVE-fix-05.04.23
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2335

#2338 Dockerfile update
  Dockerfile
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2338

#2339 FortifyScan-afterSuccess
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2339

#2343 Removal of security.sh
  dependency-check-suppressions.xml
  security.sh
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2343

#2344 Removal security sh file
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2344

#2348 Removal of security.sh
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2348

#2336 SSCS-11586 : Turn off hearing booked and reminder emails and SMS
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/NotificationConfigTestIt.java
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/tya/NotificationsIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ReminderNotificationsFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/JointPartyFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/NotificationsFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WelshNotificationsFunctionalTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/WithRepresentativePersonalisationTest.java
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2336
