Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2023-07, with the labels that each got.

#2397 CVE Fix - 03.07.23
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2397

#2400 Gradle dependencies and suppressions cleanup
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2400

#2402 Jackson revert
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2402

#2379 SSCS-10604 / SSCS-11175 / SSCS-10577 : Notify party on receipt of a request
  build.gradle
  dependency-check-suppressions.xml
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationEventTypeLists.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/PersonalisationMappingConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
  src/main/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactory.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/ActionFurtherEvidencePersonalisation.java
  src/main/java/uk/gov/hmcts/reform/sscs/personalisation/Personalisation.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/LetterUtils.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationSender.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationUtils.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SaveCorrespondenceAsyncService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/ActionFurtherEvidencePersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/LetterUtilsTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2379

#2403 Added test to verify deserialisation of localdatetime
  src/test/java/uk/gov/hmcts/reform/sscs/service/scheduler/CcdActionExecutorTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2403

#2408 CVE Fix - 31.07.2023
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2408

#2380 SSCS-11715 - Application Insights and Java 17 Upgrade
  .gitignore
  Dockerfile
  build.gradle
  charts/sscs-tya-notif/Chart.yaml
  charts/sscs-tya-notif/values.yaml
  dependency-check-suppressions.xml
  lib/AI-Agent.xml
  lib/applicationinsights.json
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2380
