Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2024-05, with the labels that each got.

#2449 SSCS-12285 - New system event postponementGranted needed
  README.md
  build.gradle
  charts/sscs-tya-notif/Chart.yaml
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/BundledNotificationsConfigTestIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
  src/e2e/resources/postponementGrantedCallback.json
  src/e2e/resources/postponementRefusedCallback.json
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationEventTypeLists.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2449

#2509 Revert "SSCS-12285 - New system event postponementGranted needed"
  README.md
  build.gradle
  charts/sscs-tya-notif/Chart.yaml
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/config/BundledNotificationsConfigTestIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/notifications/DocmosisWithGovNotifyLetterFunctionalTest.java
  src/e2e/resources/actionPostponementRequestCallback.json
  src/e2e/resources/postponementRefusedCallback.json
  src/main/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/NotificationEventTypeLists.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/notify/NotificationEventType.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SendNotificationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/callback/handlers/FilterNotificationsEventsHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/PersonalisationFactoryTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/personalisation/PersonalisationTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/NotificationServiceTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2509

#2505 Upgrade snakeyaml to 2.0 - CVE-2022-1471
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tya-notif-pr-2505

#2512 SSCSCI-874 Update suppression date
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2512

#2513 SSCSCI-874: Azure resource manager tf fix
  infrastructure/state.tf
Labels: ns:sscs, prd:sscs, aat/no-changes, prod/no-changes, rel:sscs-tya-notif-pr-2513
