Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2024-08, with the labels that each got.

#2531 SSCSCI-957 dependency check bump
  build.gradle
  config/owasp/suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tya-notif-pr-2531

#2533 SSCSSI-225: upgraded commons
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2533

#2534 Fortify issue fix
  src/main/java/uk/gov/hmcts/reform/sscs/servicebus/messaging/MessagingConfig.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2534

#2539 Update suppression date
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2539
