Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2024-02, with the labels that each got.

#2461 SSCSCI-662
  infrastructure/main.tf
Labels: ns:sscs, prd:sscs, destroy, rel:sscs-tya-notif-pr-2461

#2433 TYA: dont send notification to other part appellant if appointee is t…
  src/main/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/NotificationService.java
  src/test/java/uk/gov/hmcts/reform/sscs/factory/CcdNotificationWrapperTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2433

#2464 Update suppression date
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2464

#2465 Updated suppressions
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2465
