Repository hmcts/sscs-track-your-appeal-notifications, pull requests merged in 2024-09, with the labels that each got.

#2501 SSCSSI-147: bypass tyan service
  charts/sscs-tya-notif/Chart.yaml
  charts/sscs-tya-notif/values.preview.template.yaml
  charts/sscs-tya-notif/values.yaml
  src/main/java/uk/gov/hmcts/reform/sscs/servicebus/messaging/MessagingConfig.java
  src/main/resources/application-aat-PRODUCTION-slot.yaml
  src/main/resources/application-aat-STAGING-slot.yaml
  src/main/resources/application-preprod-STAGING-slot.yaml
  src/main/resources/application-preview-PRODUCTION-slot.yaml
  src/main/resources/application-preview-STAGING-slot.yaml
  src/main/resources/application-prod-PRODUCTION-slot.yaml
  src/main/resources/application-prod-STAGING-slot.yaml
  src/main/resources/application.yaml
Labels: ns:sscs, prd:sscs, enable_keep_helm, rel:sscs-tya-notif-pr-2501

#2546 Remove Jenkins logs being shipped to appinsights
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2546

#2540 common version bump to update huddersfield venue address
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2540

#2545 SSCSSI-313 & SSCSSI-315 Fix broken trigger in mergeReasonableAdjustme…
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tya-notif-pr-2545
